name: Build FFmpeg

on:
  schedule:
    - cron: "0 6 * * *" # Runs every day
  workflow_dispatch: # Allows manual triggering
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ffmpeg-builder-psy
    env:
      #      CC: gcc-14
      #      CXX: g++-14
      CFLAGS: -O2 -pipe -flto=auto
      CXXFLAGS: -O2 -pipe -flto=auto
      LDFLAGS: -O2 -pipe -flto=auto
    steps:
      - name: Compare Commits
        run: |
          sudo apt-get update
          sudo apt-get install -y libdav1d-dev libaom-dev libfdk-aac-dev libvpx-dev libopus-dev libx264-dev libx265-dev zip
          mkdir bin

          git clone --depth 1 https://github.com/gianni-rosato/svt-av1-psy.git  
          mkdir bin
          cd svt-av1-psy
          cd Build
          PATH="$HOME/bin:$PATH" cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$HOME/ffmpeg_build" -DCMAKE_BUILD_TYPE=Release -DBUILD_DEC=OFF -DBUILD_SHARED_LIBS=OFF .. && \
          PATH="$HOME/bin:$PATH" make -j$(nproc) && \
          make install
          cd ../..
          wget -O x265.tar.bz2 https://bitbucket.org/multicoreware/x265_git/get/master.tar.bz2 && \
          tar xjvf x265.tar.bz2 && \
          cd multicoreware*/build/linux && \
          PATH="$HOME/bin:$PATH" cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$HOME/ffmpeg_build" -DENABLE_SHARED=off ../../source && \
          PATH="$HOME/bin:$PATH" make -j$(nproc) && \
          make install
          cd ../../..
          git -C x264 pull 2> /dev/null || git clone --depth 1 https://code.videolan.org/videolan/x264.git && \
          cd x264 && \
          PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --prefix="$HOME/ffmpeg_build" --bindir="$HOME/bin" --enable-static --enable-pic && \
          PATH="$HOME/bin:$PATH" make -j$(nproc) && \
          make install
          cd ..
          git -C opus pull 2> /dev/null || git clone --depth 1 https://github.com/xiph/opus.git && \
          cd opus && \
          ./autogen.sh && \
          ./configure --prefix="$HOME/ffmpeg_build" --disable-shared && \
          make -j$(nproc) && \
          make install
          cd ..
          git -C libvpx pull 2> /dev/null || git clone --depth 1 https://chromium.googlesource.com/webm/libvpx.git && \
          cd libvpx && \
          PATH="$HOME/bin:$PATH" ./configure --prefix="$HOME/ffmpeg_build" --disable-examples --disable-unit-tests --enable-vp9-highbitdepth --as=yasm && \
          PATH="$HOME/bin:$PATH" make -j$(nproc) && \
          make install
          cd ..
          git -C fdk-aac pull 2> /dev/null || git clone --depth 1 https://github.com/mstorsjo/fdk-aac && \
          cd fdk-aac && \
          autoreconf -fiv && \
          ./configure --prefix="$HOME/ffmpeg_build" --disable-shared && \
          make -j$(nproc) && \
          make install
          cd ..
          git -C dav1d pull 2> /dev/null || git clone --depth 1 https://code.videolan.org/videolan/dav1d.git && \
          mkdir -p dav1d/build && \
          cd dav1d/build && \
          meson setup -Denable_tools=false -Denable_tests=false --default-library=static .. --prefix "$HOME/ffmpeg_build" --libdir="$HOME/ffmpeg_build/lib" && \
          ninja && \
          ninja install
          cd ..
          git -C aom pull 2> /dev/null || git clone --depth 1 https://aomedia.googlesource.com/aom && \
          mkdir -p aom_build && \
          cd aom_build && \
          PATH="$HOME/bin:$PATH" cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX="$HOME/ffmpeg_build" -DENABLE_TESTS=OFF -DENABLE_NASM=on ../aom && \
          PATH="$HOME/bin:$PATH" make -j$(nproc) && \
          make install
          cd ..
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg
          git checkout master

          export LD_LIBRARY_PATH+=":/usr/local/lib"
          PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure   --extra-cflags="-I$HOME/ffmpeg_build/include" --extra-ldflags="-L$HOME/ffmpeg_build/lib" --extra-libs="-lpthread -lm" --enable-gpl --enable-libx264 --enable-libx265 --enable-libvpx --enable-libfdk-aac --enable-libmp3lame --enable-libopus --enable-libvorbis --enable-libass --enable-libsvtav1 --enable-libaom --enable-libdav1d --enable-nonfree --enable-static --pkg-config-flags="--static" --disable-shared
          make -j$(nproc)
          ./ffmpeg -version

      - name: Package FFmpeg
        run: |
          cd ffmpeg
          mkdir ffmpeg-package
          cp ./ffmpeg ffmpeg-package/
          cp ./ffprobe ffmpeg-package/
          zip -r ../ffmpeg-package.zip ffmpeg-package

      - name: Get current date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ffmpeg-package.zip
          tag_name: ${{ env.DATE }}
